#install.packages("plyr", repos="http://cran.rstudio.com/")
#install.packages("Rcpp", repos="http://cran.rstudio.com/")
#install.packages("pbkrtest", repos="http://cran.rstudio.com/")
#install.packages("lme4", repos="http://cran.rstudio.com/")
#install.packages("scales", repos="http://cran.rstudio.com/")
#install.packages("reshape2", repos="http://cran.rstudio.com/")
#install.packages("ggplot2", repos="http://cran.rstudio.com/")
#install.packages("car", repos="http://cran.rstudio.com/")
#install.packages("BradleyTerry2", repos="http://cran.rstudio.com/")
#install.packages("e1071", repos="http://cran.rstudio.com/")
#install.packages("caret", repos="http://cran.rstudio.com/")
#install.packages("kernlab", repos="http://cran.rstudio.com/")
install.packages("HDclassif", repos="http://cran.rstudio.com/")
install.packages("pROC", repos="http://cran.rstudio.com/")
library("plyr")
library("Rcpp")
library("pbkrtest")
library("lme4")
library("scales")
library("reshape2")
library("ggplot2")
library("car")
library("BradleyTerry2")
library("e1071")
library("caret")
library("kernlab")
library("hda")
library("ada")
library("HDclassif")
library("pROC")
x_data<-read.csv(file="Discussion_Characteristics.csv",head=TRUE,sep=",")
ctrl <- trainControl(method="cv", savePred=T, classProb=T, number=10)
#All Discussion Characteristics
mod <- train(factor(Grade,levels=c("FA","GA","B","C"))~Thread_Count+Comment_Count+Contributor_Count+Anonymous_Contributor_Count+Discussion_Period+Avg_Depth+Skewness_Depth+Avg_ReadingComplexity+Skewness_ReadingComplexity+Avg_TimeGap+Skewness_TimeGap+Gini+Acknowledgement+Others+References+Images+Format+Appreciation+Summary+Suggestion+Clarification+mean_pos+median_pos+skewness_pos+mean_neg+median_neg+skewness_neg, data=x_data, method = "hdda", trControl = ctrl)
print(mod$results)
print(mod$resample)
print(mod$finalModel)
table(pred=mod$pred$pred, true=mod$pred$obs)
print(varImp(mod))
